### ISSUE TITLE
3.1 Release?

### ISSUE THREAD

**Issue by d-air1** [soreau/catt-qt#10]
Hey its me again, I was just wandering if you could do a 3.1 release, so that I don't need to use a patch file when downloading from pypi.

**Comment by soreau** [comment]
I'm running into this problem `ERROR: catt 0.12.7 has requirement pychromecast==9.2.0, but you'll have pychromecast 12.1.4 which is incompatible.`. Basically latest catt doesn't work with latest pychromecast, so I'm not really sure what to do about this, but it's blocking release.

**Comment by d-air1** [comment]
I see. I'll try and look into it as well. I believe the latest version of catt is 0.12.9 now. They have had multiple updates in the last few days, so that may cause even further problems.

**Comment by soreau** [comment]
You're right, I was able to upgrade catt and pychromecast but now when I try to build catt-qt, I get `python3.8/site-packages/requests/__init__.py:109: RequestsDependencyWarning: urllib3 (1.26.9) or chardet (5.0.0)/charset_normalizer (2.0.0) doesn't match a supported version!` and I upgraded chardet and requests packages but it didn't help. At the end it says `ModuleNotFoundError: No module named 'chardet'` even though it's installed (I suspect the wrong version is installed, but not sure which to downgrade to..).

**Comment by soreau** [comment]
I am using `flit install` from the catt-qt directory, which must pass to release.

**Comment by d-air1** [comment]
I'm currently using python 3.10, catt 0.12.9, pychromecast 12.1.4, pyqt5 5.15.7 as catt-qt's dependencies. The application runs, but crashes with
`Scanning network for Chromecast devices..
Traceback (most recent call last):
File "/home/d-air1/Documents/Experiments/build/cattqt-3.0/cattqt/cattqt.py", line 402, in run
self.s.devices = catt.api.discover()
File "/usr/lib/python3.10/site-packages/catt/api.py", line 167, in discover
return [CattDevice(ip_addr=c.ip) for c in get_casts()]
File "/usr/lib/python3.10/site-packages/catt/api.py", line 167, in <listcomp>
return [CattDevice(ip_addr=c.ip) for c in get_casts()]
AttributeError: 'Chromecast' object has no attribute 'ip'
fish: Job 1, 'python cattqt.py' terminated by signal SIGABRT (Abort)`

**Comment by soreau** [comment]
This looks like pychromecast has made some changes that catt-qt would have to adapt to.

**Comment by d-air1** [comment]
For catt's dependencies I have click at 8.1.3, ifaddr 0.1.7,  netifaces 0.11.0, requests 2.27.1.

**Comment by d-air1** [comment]
My dependencies are the newest that I know of, but I don't have the error that you have. What combination of dependency versions are you using?

**Comment by d-air1** [comment]
Let me clone the directory and try with flit install

**Comment by d-air1** [comment]
I tried using flit, but I just get ModuleNotFoundError: No module named 'cattqt'. I'm probably not doing something right.

**Comment by d-air1** [comment]
I'll try again tomorrow after work.

**Comment by soreau** [comment]
I fiddled with it for awhile and found cattqt/__init__.py needs `from .cattqt import cattqt` but now protobuf can't find the six module, even though it's installed.

**Comment by d-air1** [comment]
Well this is certainly a rabbit hole. I'll see what happens on my end.

**Comment by d-air1** [comment]
Even adding the . doesn't fix the module not found error for me.

**Comment by soreau** [comment]
Ah yes, that's not the correct solution. But did finally get it to install here, will try to publish tomorrow.

**Comment by d-air1** [comment]
Ok cool, mind telling me how you solved it as well? I'm interested in knowing what the problem was.

**Comment by soreau** [comment]
Basically I had to add `cattqt` as a dependency in cattqt/pyproject.toml but also made some other changes I'm not sure that mattered. I assume a flit update called for a need to do this explicitly, but that's just a guess, I have no idea which version this changed in, but seems undocumented.

**Comment by d-air1** [comment]
Well I'm impressed you figured it out so quickly. I wouldn't have guessed flit was the culprit.

**Comment by soreau** [comment]
Yea but this doesn't mean it runs.. looks like there's more work to be done yet.

**Comment by d-air1** [comment]
Oh. Alright, lets tackle it tomorrow then.

**Comment by d-air1** [comment]
I see you submitted a pr upstream. What's left to do on this issue?

**Comment by soreau** [comment]
The PR fixed that specific issue but catt-qt needed serious patching to get it working again. I have it mostly figured out, but the progress bar isn't working fully (when casting stuff like hulu from another device) so I want to investigate that a bit more before moving forward with a release.

In any event, [here](http://ix.io/41ax)'s the cattqt.py file I have upgraded currently.

**Comment by d-air1** [comment]
Alright. I'll play around with it when I get some time.

**Comment by soreau** [comment]
I've been tinkering and think I have the bugs shaken out with updated pychromecast. The link above contains the latest code. Considering how many major changes had to be made, I think the next release will be 4.0. I'm testing my code now, and if I don't find any other major issues, I'll release 4.0 soon.

**Comment by d-air1** [comment]
Also, when you say the link above, do you mean the one in this comment?

> The PR fixed that specific issue but catt-qt needed serious patching to get it working again. I have it mostly figured out, but the progress bar isn't working fully (when casting stuff like hulu from another device) so I want to investigate that a bit more before moving forward with a release.
> 
> In any event, [here](http://ix.io/41ax)'s the cattqt.py file I have upgraded currently.

**Comment by d-air1** [comment]
I also replied via email, but that comment didn't show up. In case it never does, I was just congratulating you on all your efforts. I look forward to viewing all the changes that are going into release 4.0.

**Comment by soreau** [comment]
> Also, when you say the link above, do you mean the one in this comment?

Yes.

**Comment by soreau** [comment]
catt-qt 4.0 released on [pypi](https://pypi.org/project/cattqt/).

**Comment by d-air1** [comment]
Wow, great work. I'll do some testing and let you know if I find anything
as well.
