### ISSUE TITLE
how to cast the subtitles 

### ISSUE THREAD

**Issue by omgbox** [soreau/catt-qt#11]
catt -s , provides srt to vtt cast 

how to cast the subtitles from the interface ?

**Comment by soreau** [comment]
This feature is not supported and not planned.

**Comment by alexandervlpl** [comment]
@soreau Would you consider a PR for this? Casting subs is probably why many people use `catt` at all.

**Comment by soreau** [comment]
@alexandervlpl If it uses a clever way without changing the ui much, then yes. It would be nice if maybe there were a right-click option to permit subtitle files.
