### ISSUE TITLE
CattQT Closing

### ISSUE THREAD

**Issue by ghost** [soreau/catt-qt#4]
Hello,
i tryed CattQT V2.6 for Windows 7 X64 the program load fine i also noticed i got chromecast sound control, 
but when i try to load a video file (.avi, .ts .mkv) or a Http HLS .m3u8 Stream, the software close without any notice,
hopefully you can resolve this issue

thanks
Jeff-

**Comment by soreau** [comment]
Hi, I think this has to do with the software I'm using to create the executable for the python script. I don't think it's including the catt program which is called when trying to play a file or link.

For now, you can either install from pypi with pip3 and run `catt-qt` to start it or clone the repo and run the script directly with python3.

**Comment by soreau** [comment]
@bigjeff22 Can you try downloading the latest executable again? It should be fixed for the windows version at least.

**Comment by ghost** [comment]
fixed the crashing issue but nothing load to my chromecast it says Playing...

**Comment by soreau** [comment]
I guess it works for me because catt is installed locally here.
