### ISSUE TITLE
error running catt-qt.exe

### ISSUE THREAD

**Issue by peefour** [soreau/catt-qt#5]
hi,

Thanks for this nice program.
I followed the instructions on the mainpage but i get an DLL Load error when executing catt-qt.exe
Any idea what is going wrong?

C:\Users\p4789\naj-py>
C:\Users\p4789\naj-py>cd "C:\Users\p4789\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\Scripts"

C:\Users\p4789\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\Scripts>catt-qt.exe
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\p4789\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\Scripts\catt-qt.exe\__main__.py", line 5, in <module>
  File "C:\Users\p4789\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\cattqt\__init__.py", line 6, in <module>
    from cattqt import cattqt
  File "C:\Users\p4789\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\cattqt\cattqt.py", line 11, in <module>
    from PyQt5.QtGui import *
ImportError: DLL load failed: The specified module could not be found.

C:\Users\p4789\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\Scripts>

**Comment by soreau** [comment]
It looks like it can't find pyqt5. I recommend using pip to install the program, as stated on the main page:
```
pip3 install catt pychromecast PyQt5 cattqt
```
You will need to install python as a prerequisite.

**Comment by peefour** [comment]
thanks for your quick reply
I did install python,
when i do it again i get following:


C:\Users\p4789\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\Scripts>pip3 install catt pychromecast PyQt5 cattqt
Requirement already satisfied: catt in c:\users\p4789\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (0.10.3)
Requirement already satisfied: pychromecast in c:\users\p4789\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (4.1.1)
Requirement already satisfied: PyQt5 in c:\users\p4789\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (5.9)
Requirement already satisfied: cattqt in c:\users\p4789\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (2.8)
Requirement already satisfied: requests>=2.18.4 in c:\users\p4789\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from catt) (2.22.0)
Requirement already satisfied: Click>=5.0 in c:\users\p4789\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from catt) (7.0)
Requirement already satisfied: youtube-dl>=2019.01.24 in c:\users\p4789\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from catt) (2020.1.24)
Requirement already satisfied: ifaddr>=0.1.4 in c:\users\p4789\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from catt) (0.1.6)
Requirement already satisfied: zeroconf>=0.17.7 in c:\users\p4789\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from pychromecast) (0.24.4)
Requirement already satisfied: casttube>=0.2.0 in c:\users\p4789\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from pychromecast) (0.2.0)
Requirement already satisfied: protobuf>=3.0.0 in c:\users\p4789\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from pychromecast) (3.11.3)
Requirement already satisfied: sip<4.20,>=4.19.3 in c:\users\p4789\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from PyQt5) (4.19.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\p4789\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from requests>=2.18.4->catt) (1.25.8)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\p4789\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from requests>=2.18.4->catt) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\p4789\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from requests>=2.18.4->catt) (2019.11.28)
Requirement already satisfied: idna<2.9,>=2.5 in c:\users\p4789\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from requests>=2.18.4->catt) (2.8)
Requirement already satisfied: setuptools in c:\program files\windowsapps\pythonsoftwarefoundation.python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\site-packages (from protobuf>=3.0.0->pychromecast) (41.2.0)
Requirement already satisfied: six>=1.9 in c:\users\p4789\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from protobuf>=3.0.0->pychromecast) (1.14.0)

C:\Users\p4789\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\Scripts>

**Comment by soreau** [comment]
In this case, perhaps you forgot to add python to your PATH? There is an option in the installer to do this for you.

**Comment by peefour** [comment]
I added it to my path via the gui installer

**Comment by peefour** [comment]
this is in the path: C:\Users\p4789\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\Scripts

**Comment by soreau** [comment]
I don't think you're supposed to run the executable directly. Try running `catt-qt`.

**Comment by peefour** [comment]
and this:
C:\Users\p4789\AppData\Local\Programs\Python\Python37\Scripts\
C:\Users\p4789\AppData\Local\Programs\Python\Python37\

**Comment by peefour** [comment]
same error:

C:\Users\p4789\naj-py>catt-qt
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\p4789\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\Scripts\catt-qt.exe\__main__.py", line 4, in <module>
  File "C:\Users\p4789\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\cattqt\__init__.py", line 6, in <module>
    from cattqt import cattqt
  File "C:\Users\p4789\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\cattqt\cattqt.py", line 11, in <module>
    from PyQt5.QtGui import *
ImportError: DLL load failed: The specified module could not be found.

C:\Users\p4789\naj-py>

**Comment by peefour** [comment]
Any idea why it is giving an DLL Load error? Which DLL it can not load?

**Comment by soreau** [comment]
Apparently it can't load PyQt5 dll. This might be a problem with your setup or installation because it doesn't have this problem when I tested with latest on windows 10.

**Comment by soreau** [comment]
Maybe something like [this](https://stackoverflow.com/questions/42863505/dll-load-failed-when-importing-pyqt5)?

**Comment by peefour** [comment]
no, i tried the suggestions there, but still same error
tx for helping!

**Comment by peefour** [comment]
I deleted and reinstalled everything and now i can run the program, but I get a small catt-qt empty box, amd then python crashes

[Python]
A problem caused the program to stop working correctly. Windows will close the program and notify you if a solution is available.

C:\Windows\system32>catt-qt
Scanning network for Chromecast devices..
No devices found
Traceback (most recent call last):
  File "c:\users\p4789\appdata\local\programs\python\python37\lib\site-packages\cattqt\cattqt.py", line 632, in focus_changed
    self.textbox.setFocus()
AttributeError: 'App' object has no attribute 'textbox'

**Comment by soreau** [comment]
Yes the same thing happens here on Windows. It works fine in Linux, so maybe there's a problem with pychromecast or catt on windows. I'll see what I can turn up.

**Comment by peefour** [comment]
thank you!
also, the log above says 'no devices found' but my chromecast is active

**Comment by soreau** [comment]
Yes, there is some bug. `catt` doesn't find any devices, which means that catt-qt wont either. I filed a catt issue about it.

**Comment by soreau** [comment]
Ok, I managed to get it working. I uninstalled python, downloaded latest 3.8.1 and installed it. Then started a new command prompt and reinstalled the packages using the pip3 install command. After that it's now working.

**Comment by peefour** [comment]
thank you
I will try it!

**Comment by peefour** [comment]
hi,

i installed the latest python 3.8.2 via the windows installer, but i get an error that references python37? is python37 it hardcoded in the script?

C:\Windows\system32>pip3 install catt pychromecast PyQt5 cattqt
Fatal error in launcher: Unable to create process using '"c:\users\p4789\appdata\local\programs\python\python37\python.exe"  "C:\Users\p4789\AppData\Local\Programs\Python\Python37\Scripts\pip3.exe" install catt pychromecast PyQt5 cattqt': The system cannot find the file specified.


C:\Windows\system32>python
Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by peefour** [comment]
i uninstalled python37, and then installed the newest python via windows installer, but still the same problem

C:\Windows\system32>catt-qt
Scanning network for Chromecast devices..
No devices found
Traceback (most recent call last):
  File "c:\users\p4789\appdata\local\programs\python\python38\lib\site-packages\cattqt\cattqt.py", line 632, in focus_changed
    self.textbox.setFocus()
AttributeError: 'App' object has no attribute 'textbox'

C:\Windows\system32>python
Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by soreau** [comment]
Did you reinstall everything with pip3 after reinstalling python? Try `pip3 install catt pychromecast PyQt5 cattqt --force-reinstall`

**Comment by peefour** [comment]
Thank you! it works now!!
Just 1 thing: it has the same icon as chrome.
I want to distinguish it in the taskbar from other chrome windows.
Can the icon be changed?

Thanks!!

**Comment by soreau** [comment]
Yes, the icon could probably use a change. You can file an issue about it. Feel free to suggest an icon.

For what it's worth, when it doesn't find any devices, it's supposed to show a window with options to scan again or quit, but there is a bug in the current release causing it to crash that will be fixed in upcoming releases.

**Comment by peefour** [comment]
Thanks man.
I would use the standard chromecast icons, as defined here: http://chromespot.com/2014/03/24/google-chromecast-icons/

you can download icons for free here: https://www.flaticon.com/free-icon/cast_566079

I will make an issue

**Comment by peefour** [comment]
> Yes, the icon could probably use a change. You can file an issue about it. Feel free to suggest an icon.

1-See my suggestions in comment above.

2-Is it possible to package this very useful application as an Windows .exe program?
That would make it easy to run and distribute it.

**Comment by soreau** [comment]
> > Yes, the icon could probably use a change. You can file an issue about it. Feel free to suggest an icon.
> 
> 1-See my suggestions in comment above.

The icon has already been changed, update to latest release.
 
> 2-Is it possible to package this very useful application as an Windows .exe program?
> That would make it easy to run and distribute it.

I tried to do this but I was unable to create a completely working binary because it needs catt to be installed and I don't know how to make a catt binary to include.
